# TBC: https://github.com/codecov/example-python
language: python
python: 3.6
install:
  - pip install plotnine
  - pip install seaborn
  - pip install pydataset
#  - pip install codecov
#  - pip install pytest pytest-cov
script:
  - pytest
## Push the results back to codecov
#after_success:
#  - codecov